#!/usr/bin/env bash
# Regenerates tools/agent_play.gd from the game's own bot (tools/playtest.gd), changed in one
# place only: frames go under debug-agent/runs/ (env DA_OUT) instead of res://screenshots.
# The game's bot is the source of truth for "how a player plays"; we never edit it.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
SRC="$ROOT/tools/playtest.gd"
DST="$ROOT/debug-agent/tools/agent_play.gd"
sed -e 's|^const OUT_DIR := "res://screenshots"|var OUT_DIR: String = OS.get_environment("DA_OUT") if OS.get_environment("DA_OUT") != "" else "res://debug-agent/runs/adhoc"|' \
    -e '1s|^# res://tools/playtest.gd|# GENERATED by debug-agent/tools/sync_harness.sh from res://tools/playtest.gd -- do not edit|' \
    "$SRC" > "$DST"
grep -q 'DA_OUT' "$DST" || { echo "sync_harness: OUT_DIR line not found in playtest.gd -- update the sed" >&2; exit 1; }
echo "synced $DST ($(wc -l < "$DST") lines)"
